### ISSUE TITLE
How to modify it?

### ISSUE THREAD

**Issue by 4dvn** [TheKikGen/kikpad#3]
Hello, thank you for this great project, can you tell my how to modify it for 4x4 buttons pad & 4x4 rgbs and 4 rotarys?

**Comment by TheKikGen** [comment]
Hello.  You mean a new design ?   
This project is specific to the lowcost Midiplus Smartpad.   
If you need to port it  to another hardware, simply study the code (c++).

**Comment by 4dvn** [comment]
> Hello. You mean a new design ?
> This project is specific to the lowcost Midiplus Smartpad.
> If you need to port it to another hardware, simply study the code (c++).

yah, i'm buying the stm32f103rbt6 for testing, but i'm still stuck to defind the rgb pinout and rgb leds type

**Comment by TheKikGen** [comment]
Maybe you should buy a Smartpad and build your project on.  It is less than 60 euros, and you have a full dev platform !!

**Comment by 4dvn** [comment]
> Maybe you should buy a Smartpad and build your project on.  It is less than 60 euros, and you have a full dev platform !!
> 
> 

Hello,
Can you sent me the example 1-2 buttons midi push handle code from this example:
https://github.com/arpruss/USBComposite_stm32f1/blob/master/examples/midiout/midiout.ino
when push the buttons sent note from note 36-37

**Comment by TheKikGen** [comment]
Hi. Ask directy the author Arpruss.  I don't use USBComposite.
